ALTER TABLE products
ADD COLUMN IF NOT EXISTS last_sales_qty INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_sales_total DECIMAL(10, 2) DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS average_sale_price DECIMAL(10, 2) DEFAULT 0.00;