-- Add is_combo flag to products table
ALTER TABLE products
ADD COLUMN IF NOT EXISTS is_combo BOOLEAN DEFAULT FALSE;
-- Create product_combos table
CREATE TABLE IF NOT EXISTS product_combos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    child_product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Index for performance
CREATE INDEX IF NOT EXISTS idx_product_combos_parent ON product_combos(parent_product_id);
CREATE INDEX IF NOT EXISTS idx_product_combos_child ON product_combos(child_product_id);